### ISSUE TITLE
authGuardLoggedInURL not working

### ISSUE THREAD

**Issue by Aqebutto** [AnthonyNahas/ngx-auth-firebaseui#423] opened 2020-01-13 10:37 UTC
Hello, and thank you for the API!

"    NgxAuthFirebaseUIModule.forRoot(firebaseConfig, firebaseAppNameFactory, {
      authGuardFallbackURL: 'home',
      authGuardLoggedInURL: 'main'
    }) "

the authGuardLoggedInURL is not triggered. When I log in and close the web site and open it again the user is logged it. I want the user to be redirected to /main. 

What am I missing? 

Here are my routes:
"const routes: Routes = [
  { path: '', redirectTo: '/home', pathMatch: 'full' },
  { path: 'home', component: HomeComponent },
  { path: 'main', component: MainComponent, canActivate: [LoggedInGuard] }
];"

Thanks in advance!

**Comment by acristobalesteban** [comment] 2020-01-25 08:05
Im also having this issue.  Where you able to figure anything out?

**Comment by jacktwork** [comment] 2020-01-29 20:37
Same here.  Something is wrong.   It appears broken or maybe I do not understand something.  Also what is this "app name factory" you're supposed to pass as a parameter to  NgxAuthFirebaseUIModule.forRoot in your app module?   Can't find any documentation on it.

**Comment by xigolle** [comment] 2020-02-08 14:23
@Aqebutto Already found a solution for this? 
I also cannot seem to figure out how it should work. 
These are my routes:
`const routes: Routes = [
  {
    path: '',
    component: LoginComponent
  },
  {
    path: 'login',
    component: LoginComponent
  },
  {
    path: 'selected-car',
    component: SelectedCarComponent,
    canActivate: [LoggedInGuard]
  },
  {
    path: '**',
    redirectTo: 'login',
  }
];
`

And this is the configuration of the redirect url:
`NgxAuthFirebaseUIModule.forRoot(environment.firebase, firebaseAppNameFactory, {
      authGuardFallbackURL: 'pages/selected-car',
      authGuardLoggedInURL: 'pages/selected-car'
    }),`

I thought it shoulld follow the folder structure that is why I have pages/...

![image](https://user-images.githubusercontent.com/4833546/74086817-ea961980-4a86-11ea-8639-7a4c9a866544.png)

Hope somebody can help me out here! :)

**Comment by jacktwork** [comment] 2020-02-08 14:36
NgxAuthFirebaseUIModule.forRoot(environment.firebase,
      () => 'myfireappname',
      {
        enableFirestoreSync: true,
        authGuardFallbackURL: '/loggedout',
        authGuardLoggedInURL: '/loggedin',
      }
    )

This finally worked for me.  It appears that factory is something someone stuck in there and did not document and it is not really needed.   myfireappname is my firebase project name without the .firebaseapp.com suffix

**Comment by xigolle** [comment] 2020-02-08 15:07
@jacktwork Thanks for replying! 
Very strange I think I did everything correct but it still doesn't seem to work? 
I did add the enableFirestoreSync to see if that was the problem:
![image](https://user-images.githubusercontent.com/4833546/74087480-f1278f80-4a8c-11ea-812e-4697a44fb46d.png)

I also add the routes with a / but this is my routing config:
![image](https://user-images.githubusercontent.com/4833546/74087486-01d80580-4a8d-11ea-96cc-db213118f99b.png)

I assume this is all set up correctly then? 
But when I refresh/enter the site/login from the form I always go to that "default" redirect page with your profile pic and sign out buttons

**Comment by acristobalesteban** [comment] 2020-02-11 01:29
Reading through the source code, this is by design.  Now, Im not sure weather this is an issue with the docs or the code.  

As you can see in the HTML, the component is not doing anything special other than your basic *ngIf
https://github.com/AnthonyNahas/ngx-auth-firebaseui/blob/master/projects/ngx-auth-firebaseui/src/lib/components/ngx-auth-firebaseui/auth.component.html . 

Further, the Logged In guard does not do anything with the authGuardLoggedInURL so the page is simply following the logic of the ngIf above.
![image](https://user-images.githubusercontent.com/57468833/74204838-74d2af00-4c3a-11ea-96fb-6fdb8e45efac.png).

In the meantime, I recommend making your own custom Auth Gaurd.

**Comment by xigolle** [comment] 2020-02-11 09:38
@acristobalesteban Thanks for the clarification about the issue here.
Already saw the guard logic which felt weird but maybe I was missing something.
Did indeed create an additional guard + logic after succesfull login to redirect the application to the right routes. 
But it is something that should be fixed/supported by the component itself I think ?

If there is somebody interested in how I did it let me know and I will post the code for the guard/redirect.

**Comment by A7madHD** [comment] 2020-02-13 00:13
After checking the source code, the guard should change from `pipe` to `.subscribe`, that will solve the issue i guess.

**Comment by rlarge** [comment] 2020-02-20 20:54
I would love to see you work as I'm currently looking at role based solution with angular-fire and Firebase functions.  Using something like [This](https://www.toptal.com/firebase/role-based-firebase-authentication).  Although its been put on hold because someone said @AnthonyNahas  they are gonna release something soon.

**Closed** 2022-10-18 21:40 UTC
Labels: PR WELCOME <3
