### ISSUE TITLE
providers: icons mis-aligned

### ISSUE THREAD

**Issue by Splaktar** [AnthonyNahas/ngx-auth-firebaseui#222] opened 2019-04-15 21:04 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### OS and Version?

macOS Mojave
### Versions

```
Angular CLI: 7.3.8
Node: 10.15.3
OS: darwin x64
Angular: 7.2.13
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.8
@angular-devkit/build-angular     0.13.8
@angular-devkit/build-optimizer   0.13.8
@angular-devkit/build-webpack     0.13.8
@angular-devkit/core              7.3.8
@angular-devkit/schematics        7.3.8
@angular/cdk                      7.3.7
@angular/cli                      7.3.8
@angular/fire                     5.1.2
@angular/flex-layout              7.0.0-beta.24
@angular/material                 7.3.7
@ngtools/webpack                  7.3.8
@schematics/angular               7.3.8
@schematics/update                0.13.8
rxjs                              6.4.0
typescript                        3.2.4
webpack                           4.29.0
```
```
"ngx-auth-firebaseui": "^2.6.0",
```

### Repro steps

1. Use `<ngx-auth-firebaseui></ngx-auth-firebaseui>` in an otherwise empty component.

<img width="1218" alt="Captura de Pantalla 2019-04-15 a la(s) 16 02 14" src="https://user-images.githubusercontent.com/3506071/56165205-fe244100-5f97-11e9-943f-0e39b4898c32.png">

It looks like Angular Material may have changed some of the DOM structure or styling of icons within buttons.

It appears to be caused by this line:

https://github.com/AnthonyNahas/ngx-auth-firebaseui/blob/ff8b86e19ee4abc7d3f0f99d2fba432e7f702585/src/module/components/providers/auth.providers.component.scss#L11

Unchecking that style in DevTools gives:
<img width="1227" alt="Captura de Pantalla 2019-04-15 a la(s) 16 02 30" src="https://user-images.githubusercontent.com/3506071/56165242-1005e400-5f98-11e9-9c81-723cd6526ab0.png">

### The log given by the failure

N/A

### Desired functionality

Provider icons aligned correctly within their buttons.

### Mention any other details that might be useful

Workaround:
1. Set `encapsulation: ViewEncapsulation.None` on your container component
1. Set this SCSS
```scss
ngx-auth-firebaseui {
  mat-icon {
    vertical-align: middle !important;
  }
}
```

**Comment by AnthonyNahas** [comment] 2019-04-16 13:58
I tested the library with chrome, opera, safari and firefox... I've couldn't reproduce this css issue...
The following ticket of a related library that has the same problem (https://github.com/angular-material-extensions/password-strength/issues/158)

If you know how to improve the css properties of `ngx-auth-firebaseui` in order to align the icons, please feel free to open a new PR

**Comment by Splaktar** [comment] 2019-04-16 20:18
Very strange. I can't reproduce this in the demo project either, even when I [updated most of the dependencies](https://github.com/AnthonyNahas/ngx-auth-firebaseui/pull/225). It certainly appears in my brand new Angular CLI project when adding `<ngx-auth-firebaseui></ngx-auth-firebaseui>`.

**Comment by Splaktar** [comment] 2019-04-16 20:22
Btw, I see this in my app with 
- Chrome Versión 73.0.3683.103 (Build oficial) (64 bits)
- Firefox 66.0.2 and 66.0.3
- Safari 12.1

**Comment by Splaktar** [comment] 2019-04-16 20:23
These changes are currently in a PR branch: https://github.com/angular-hispano/angular-hispano/pull/23

**Comment by AnthonyNahas** [comment] 2019-04-17 07:54
give some extra time to find the issue ...

**Comment by Splaktar** [comment] 2019-04-27 17:21
Related to https://github.com/angular/components/issues/8842

**Comment by AnthonyNahas** [comment] 2019-04-27 19:08
How can we fix that ? 

if I remove `mat-icon {
    vertical-align: inherit;
  }`

this would not be rendered correctly in my apps. 
However, this would maybe work only for apps that have been created new from scratch..

I've added a new demo app

`ng new demo`
`ng add @angular/material`
`ng add ngx-auth-firebaseui`

and you had right.. the icons will be mis-aligned...

**Comment by maartentibau** [comment] 2019-09-08 10:20
My Solution for this currently is this:

```scss
::ng-deep span.mat-button-wrapper {
  display: flex;
  justify-content: center;
  align-items: center;

  & > mat-icon {
    margin-right: 8px;
  }
}
```

**Comment by michalowskil** [comment] 2019-11-27 11:44
This is related to Bootstrap. Issue appears only when I remove Bootstrap CSS from angular.json:


```
"styles": [ 
    "node_modules/bootstrap/dist/css/bootstrap.min.css", 
    "./node_modules/@angular/material/prebuilt-themes/indigo-pink.css", 
    "src/styles.scss" 
],
```

Remember that "ng serve" restart is needed if you edit angular.json.

**Comment by AnthonyNahas** [comment] 2019-11-28 18:43
That means bootstrap is manipulating some css properties ?

**Comment by michalowskil** [comment] 2019-11-28 20:41
After installing Bootstrap the problem disappears, so I guess it changes some properties.
Maybe you created ngx-auth-firebaseui with Bootstrap installed?

**Comment by AnthonyNahas** [comment] 2019-11-28 20:52
yeah, the demo app has bootstrap too :(

but I have many many other project without bootstrap, and that is working fine without any issues...

**Comment by AnthonyNahas** [comment] 2020-02-13 22:13
this is now fixed in v4! 

The release is soon!

@Splaktar you had right! ` vertical-align: inherit; ` this was the problem! It has an issue indirectly with bootstrap apps!

cheers 🍻

**Comment by AnthonyNahas** [comment] 2020-02-16 20:00
v4 is now release 

https://github.com/AnthonyNahas/ngx-auth-firebaseui/releases/tag/4.0.0
https://www.npmjs.com/package/ngx-auth-firebaseui

this should be fixed now 
congrats all <3

**Closed by AnthonyNahas** 2020-02-16 20:00 UTC
Labels: bug, ready
