### ISSUE TITLE
Providers icons are vertically aligned to TOP instead of middle

### ISSUE THREAD

**Issue by dev-mansonthomas** [AnthonyNahas/ngx-auth-firebaseui#355] opened 2019-09-19 22:56 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### OS and Version?
MacOs Mojave 10.14.6 (18G95), Chrome  77.0.3865.90

### Versions
```
ng --version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 8.3.5
Node: 10.16.2
OS: darwin x64
Angular: 8.2.7
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.5
@angular-devkit/build-angular     0.803.5
@angular-devkit/build-optimizer   0.803.5
@angular-devkit/build-webpack     0.803.5
@angular-devkit/core              8.3.5
@angular-devkit/schematics        8.3.5
@angular/cdk                      8.2.0
@angular/cli                      8.3.5
@angular/fire                     5.2.1
@angular/flex-layout              8.0.0-beta.26
@angular/material                 8.2.0
@ngtools/webpack                  8.3.5
@schematics/angular               8.3.5
@schematics/update                0.803.5
rxjs                              6.5.3
typescript                        3.5.3
webpack                           4.39.2
```

### Repro steps
including the component very basically : 
```
<ngx-auth-firebaseui (onSuccess)="printUser($event)"
                     (onError)="printError($event)">
</ngx-auth-firebaseui>
```

the images of providers (google, ms, fb etc...) are vertically aligned  to TOP.

![image](https://user-images.githubusercontent.com/5695269/65286721-dc2f7b80-db40-11e9-9fb8-e913fbf3ef16.png)

### The log given by the failure
no log

### Desired functionality
vertical align should be in the middle.

### Mention any other details that might be useful
login code is here :
https://github.com/dev-mansonthomas/RedCrossQuestFrontEnd/tree/master/src/app/authentication/login

**Comment by AnthonyNahas** [comment] 2019-10-09 20:25
duplicate of #222

**Closed by AnthonyNahas** 2019-10-09 20:25 UTC
Labels: duplicate
