### ISSUE TITLE
Compatibility with `firebase` v9 and `@angular/fire` v7

### ISSUE THREAD

**Issue by gkalpak** [AnthonyNahas/ngx-auth-firebaseui#631] opened 2021-09-01 16:51 UTC
Just a heads-up that this package is not compatible with the latest versions of `firebase` (v9) and `@angular/fire` (v7), due to them introducing several [breaking changes][1].

In the short term, making a package compatible with the latest versions of `firebase` and `@angular/fire` could be just a matter of [updating the import paths][2].

[1]: https://github.com/angular/angularfire/blob/db76d50de5a9be98a33eb4fefebf5d2c14515cfe/docs/version-7-upgrade.md
[2]: https://github.com/angular/angularfire/blob/db76d50de5a9be98a33eb4fefebf5d2c14515cfe/docs/version-7-upgrade.md#compatibility-mode

**Comment by chriscurnow** [comment] 2021-11-11 04:34
I have created PR #638 which seems to work.

**Comment by osterland** [comment] 2021-12-14 22:45
look like your pr got merged, but when adding version 5.3.0 i get the same errors. Any Tips how i can get your version? 
TY

**Comment by mattpenner** [comment] 2021-12-30 09:50
How are others currently unit testing their firebase rules? I am attempting to start doing this but I'm hitting roadblocks and haven't been successfully able to do so. All the latest firebase testing packages are built on v9. The older packages that target v8 don't seem to work with Angular 12+. At this point it seems that I can't unit test firebase if I'm using ngx-auth. 

@AnthonyNahas is there some help we might provide to get a new release of ngx-auth published with the latest PRs? Testing, documentation updates, etc.?  Let us know if the community here can help out in some ways. 

My next step is to build locally, pack and include the local version in our project and see if this will help us upgrade to v9.

**Comment by mattpenner** [comment] 2021-12-31 20:29
@CiriousJoker I cloned the repo, which contains your PR.  I then ran npm run build:lib to build the library.  I then used npm link in the dist folder to link it.

When I import it into my project and attempt to build I get the following error twice:
```
⠋ Generating browser application bundles (phase: setup)...
Compiling ngx-auth-firebaseui : es2015 as esm2015

An error occurred during the build:
Error: Failed to compile entry-point ngx-auth-firebaseui (`es2015` as esm2015) due to compilation errors:
node_modules/ngx-auth-firebaseui/fesm2015/ngx-auth-firebaseui.js:1634:26 - error NG1010: Value at position 22 in the NgModule.imports of NgxAuthFirebaseUIModule is not a reference
  Value could not be determined statically.

1634                 imports: [
                              ~
1635                     CommonModule,
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ...
1664                     AngularFirestoreModule,
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1665                 ],
     ~~~~~~~~~~~~~~~~~

  node_modules/ngx-auth-firebaseui/fesm2015/ngx-auth-firebaseui.js:1663:21
    1663                     AngularFireAuthModule,
                             ~~~~~~~~~~~~~~~~~~~~~
    Unknown reference.
```

Were you able to successfully build a project that imports the package with your changes? I'm doing a lot of research but not finding what the issue is that is causing this.

**Comment by docaohuynh** [comment] 2022-01-01 07:10
@mattpenner  I have same problem

**Comment by CiriousJoker** [comment] 2022-01-01 23:40
Idk, sorry. I ended up going back to the old version in the meantime.

**Comment by Judp0m** [comment] 2022-02-05 00:25
Also blocked by this... Have to decide between waiting for this package to be upgraded to support v9 (at least via Compat mode, preferably via Modular mode to get the size reduction benefits) or dropping the dependency.

**Comment by mattpenner** [comment] 2022-02-05 00:36
Agreed. We are getting close to being forced to make that decision. 

@AnthonyNahas I would be happy to try and help assist with the upgrade but I would need some assistance getting familiar with the package. Without the testing in place and my lack of familiarity with some of the features we don't use the last thing I would want to do is submit a patch and call it done only to break some parts for others. I can help but it will require some joint time for education on the project.

**Comment by AnthonyNahas** [comment] 2022-02-15 22:30
https://www.npmjs.com/package/ngx-auth-firebaseui v6 is now live

this is fixed now

thank you<3

**Closed by AnthonyNahas** 2022-02-15 22:30 UTC
Labels: feature
